#!/bin/bash

# Installs/upgrades Dock in /usr/local/bin/dock, requiring sudo password only
# if necessary.
#
# You can run it anywhere by executing:
#
#    curl https://raw.githubusercontent.com/brigade/dock/master/script/install-dock | bash

set -euo pipefail

location=/usr/local/bin/dock
sudo=""

auth-sudo() {
  if ! sudo -n >/dev/null 2>&1; then
    echo "Enter your sudo password to install Dock in $location"
    sudo -v
    sudo="sudo"
  fi
}

if [ ! -d $(dirname $location) ]; then
  mkdir_cmd="mkdir -p $location"
  if ! $mkdir_cmd >/dev/null 2>&1; then
    auth-sudo
    sudo $mkdir_cmd
  fi
fi

if ! touch $location; then
  auth-sudo
  sudo touch $location
  sudo chown $(id -u):$(id -g) $location
fi

if ! chmod +x $location; then
  auth-sudo
  sudo chmod +x $location
fi

$sudo curl -L https://raw.githubusercontent.com/brigade/dock/master/bin/dock --output $location
